// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://uuobiqyoxuemklhtyycn.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1b2JpcXlveHVlbWtsaHR5eWNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzExMDUwNjAsImV4cCI6MjA0NjY4MTA2MH0.Vq7IfQU4TzfIn30PJ1BDOnBMEXFUyEHpmdhB-H3n-kY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);